SOFUS: swig_runtime.h File Reference
swig_runtime.h File Reference
#include <string.h>
Classes
struct swig_type_info
struct swig_cast_info
struct swig_module_info
struct swig_const_info
struct SwigPyClientData
struct SwigPyObject
struct SwigPyPacked
Macros
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGINLINE
#define SWIGUNUSED
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGEXPORT
#define SWIGSTDCALL
#define SWIG_UnknownError -1
#define SWIG_IOError -2
#define SWIG_RuntimeError -3
#define SWIG_IndexError -4
#define SWIG_TypeError -5
#define SWIG_DivisionByZero -6
#define SWIG_OverflowError -7
#define SWIG_SyntaxError -8
#define SWIG_ValueError -9
#define SWIG_SystemError -10
#define SWIG_AttributeError -11
#define SWIG_MemoryError -12
#define SWIG_NullReferenceError -13
#define SWIG_RUNTIME_VERSION "4"
#define SWIG_TYPE_TABLE_NAME
#define SWIGRUNTIME SWIGINTERN
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#define SWIG_BUFFER_SIZE 1024
#define SWIG_POINTER_DISOWN 0x1
#define SWIG_CAST_NEW_MEMORY 0x2
#define SWIG_POINTER_NO_NULL 0x4
#define SWIG_POINTER_OWN 0x1
#define SWIG_OK (0)
#define SWIG_ERROR (-1)
#define SWIG_IsOK(r) (r >= 0)
#define SWIG_ArgError(r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
#define SWIG_CASTRANKLIMIT (1 << 8)
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
#define SWIG_BADOBJ (SWIG_ERROR)
#define SWIG_OLDOBJ (SWIG_OK)
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
#define SWIG_AddNewMask(r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
#define SWIG_AddCast(r) (r)
#define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#define Py_TYPE(op) ((op)->ob_type)
#define SWIG_Python_str_FromFormat PyString_FromFormat
#define SWIG_Python_str_DelForPy3(x)
#define PyObject_DEL PyObject_Del
#define SWIGPY_USE_CAPSULE
#define SWIGPY_CAPSULE_NAME ("swig_runtime_data" SWIG_RUNTIME_VERSION ".type_pointer_capsule" SWIG_TYPE_TABLE_NAME)
#define PyDescr_TYPE(x) (((PyDescrObject *)(x))->d_type)
#define PyDescr_NAME(x) (((PyDescrObject *)(x))->d_name)
#define Py_hash_t long
#define SWIG_PYTHON_INITIALIZE_THREADS
#define SWIG_PYTHON_THREAD_BEGIN_BLOCK
#define SWIG_PYTHON_THREAD_END_BLOCK
#define SWIG_PYTHON_THREAD_BEGIN_ALLOW
#define SWIG_PYTHON_THREAD_END_ALLOW
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY 5
#define SWIG_Python_ConvertPtr(obj, pptr, type, flags) SWIG_Python_ConvertPtrAndOwn(obj, pptr, type, flags, 0)
#define SWIG_ConvertPtr(obj, pptr, type, flags) SWIG_Python_ConvertPtr(obj, pptr, type, flags)
#define SWIG_ConvertPtrAndOwn(obj, pptr, type, flags, own) SWIG_Python_ConvertPtrAndOwn(obj, pptr, type, flags, own)
#define SWIG_NewPointerObj(ptr, type, flags) SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
#define SWIG_InternalNewPointerObj(ptr, type, flags) SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
#define SWIG_CheckImplicit(ty) SWIG_Python_CheckImplicit(ty)
#define SWIG_AcquirePtr(ptr, src) SWIG_Python_AcquirePtr(ptr, src)
#define swig_owntype int
#define SWIG_ConvertPacked(obj, ptr, sz, ty) SWIG_Python_ConvertPacked(obj, ptr, sz, ty)
#define SWIG_NewPackedObj(ptr, sz, type) SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_ConvertInstance(obj, pptr, type, flags) SWIG_ConvertPtr(obj, pptr, type, flags)
#define SWIG_NewInstanceObj(ptr, type, flags) SWIG_NewPointerObj(ptr, type, flags)
#define SWIG_ConvertFunctionPtr(obj, pptr, type) SWIG_Python_ConvertFunctionPtr(obj, pptr, type)
#define SWIG_NewFunctionPtrObj(ptr, type) SWIG_Python_NewPointerObj(NULL, ptr, type, 0)
#define SWIG_ConvertMember(obj, ptr, sz, ty) SWIG_Python_ConvertPacked(obj, ptr, sz, ty)
#define SWIG_NewMemberObj(ptr, sz, type) SWIG_Python_NewPackedObj(ptr, sz, type)
#define SWIG_GetModule(clientdata) SWIG_Python_GetModule(clientdata)
#define SWIG_SetModule(clientdata, pointer) SWIG_Python_SetModule(pointer)
#define SWIG_NewClientData(obj) SwigPyClientData_New(obj)
#define SWIG_SetErrorObj SWIG_Python_SetErrorObj
#define SWIG_SetErrorMsg SWIG_Python_SetErrorMsg
#define SWIG_ErrorType(code) SWIG_Python_ErrorType(code)
#define SWIG_Error(code, msg) SWIG_Python_SetErrorMsg(SWIG_ErrorType(code), msg)
#define SWIG_fail goto fail
#define SWIG_Python_Raise(obj, type, desc) SWIG_Python_SetErrorObj(SWIG_Python_ExceptionType(desc), obj)
#define SWIG_Python_CallFunctor(functor, obj) PyObject_CallFunction(functor, (char *)"O", obj);
#define SWIG_STATIC_POINTER(var) var = 0; if (!var) var
#define SWIG_POINTER_NOSHADOW (SWIG_POINTER_OWN << 1)
#define SWIG_POINTER_NEW (SWIG_POINTER_NOSHADOW | SWIG_POINTER_OWN)
#define SWIG_POINTER_IMPLICIT_CONV (SWIG_POINTER_DISOWN << 1)
#define SWIG_BUILTIN_TP_INIT (SWIG_POINTER_OWN << 2)
#define SWIG_BUILTIN_INIT (SWIG_BUILTIN_TP_INIT | SWIG_POINTER_OWN)
#define SWIG_POINTER_EXCEPTION 0
#define SWIG_arg_fail(arg) SWIG_Python_ArgFail(arg)
#define SWIG_MustGetPtr(p, type, argnum, flags) SWIG_Python_MustGetPtr(p, type, argnum, flags)
Typedefs
typedef void *(* swig_converter_func) (void *, int *)
typedef struct swig_type_info *(* swig_dycast_func) (void **)
typedef struct swig_type_info swig_type_info
typedef struct swig_cast_info swig_cast_info
typedef struct swig_module_info swig_module_info
typedef struct swig_const_info swig_const_info
Functions
SWIGRUNTIME int SWIG_TypeNameComp (const char *f1, const char *l1, const char *f2, const char *l2)
SWIGRUNTIME int SWIG_TypeCmp (const char *nb, const char *tb)
SWIGRUNTIME int SWIG_TypeEquiv (const char *nb, const char *tb)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheck (const char *c, swig_type_info *ty)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheckStruct (swig_type_info *from, swig_type_info *ty)
SWIGRUNTIMEINLINE void * SWIG_TypeCast (swig_cast_info *ty, void *ptr, int *newmemory)
SWIGRUNTIME swig_type_info * SWIG_TypeDynamicCast (swig_type_info *ty, void **ptr)
SWIGRUNTIMEINLINE const char * SWIG_TypeName (const swig_type_info *ty)
SWIGRUNTIME const char * SWIG_TypePrettyName (const swig_type_info *type)
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME swig_type_info * SWIG_MangledTypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME swig_type_info * SWIG_TypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME char * SWIG_PackData (char *c, void *ptr, size_t sz)
SWIGRUNTIME const char * SWIG_UnpackData (const char *c, void *ptr, size_t sz)
SWIGRUNTIME char * SWIG_PackVoidPtr (char *buff, void *ptr, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackVoidPtr (const char *c, void **ptr, const char *name)
SWIGRUNTIME char * SWIG_PackDataName (char *buff, void *ptr, size_t sz, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackDataName (const char *c, void *ptr, size_t sz, const char *name)
SWIGINTERN char * SWIG_Python_str_AsChar (PyObject *str)
SWIGINTERN PyObject * SWIG_Python_str_FromChar (const char *c)
SWIGRUNTIME PyObject * SWIG_Python_ErrorType (int code)
SWIGRUNTIME void SWIG_Python_AddErrorMsg (const char *mesg)
SWIGRUNTIME int SWIG_Python_TypeErrorOccurred (PyObject *obj)
SWIGRUNTIME void SWIG_Python_RaiseOrModifyTypeError (const char *message)
SWIGINTERN void SWIG_Python_SetErrorObj (PyObject *errtype, PyObject *obj)
SWIGINTERN void SWIG_Python_SetErrorMsg (PyObject *errtype, const char *msg)
SWIGINTERN void SWIG_Python_SetConstant (PyObject *d, const char *name, PyObject *obj)
SWIGINTERN PyObject * SWIG_Python_AppendOutput (PyObject *result, PyObject *obj)
SWIGINTERN Py_ssize_t SWIG_Python_UnpackTuple (PyObject *args, const char *name, Py_ssize_t min, Py_ssize_t max, PyObject **objs)
SWIGRUNTIMEINLINE PyObject * SWIG_Py_Void (void)
SWIGRUNTIMEINLINE int SWIG_Python_CheckImplicit (swig_type_info *ty)
SWIGRUNTIMEINLINE PyObject * SWIG_Python_ExceptionType (swig_type_info *desc)
SWIGRUNTIME SwigPyClientData * SwigPyClientData_New (PyObject *obj)
SWIGRUNTIME void SwigPyClientData_Del (SwigPyClientData *data)
SWIGRUNTIME PyObject * SwigPyObject_long (SwigPyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_format (const char *fmt, SwigPyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_oct (SwigPyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_hex (SwigPyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_repr (SwigPyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_repr2 (PyObject *v, PyObject *SWIGUNUSEDPARM(args))
SWIGRUNTIME int SwigPyObject_compare (SwigPyObject *v, SwigPyObject *w)
SWIGRUNTIME PyObject * SwigPyObject_richcompare (SwigPyObject *v, SwigPyObject *w, int op)
SWIGRUNTIME PyTypeObject * SwigPyObject_TypeOnce (void)
SWIGRUNTIME PyTypeObject * SwigPyObject_type (void)
SWIGRUNTIMEINLINE int SwigPyObject_Check (PyObject *op)
SWIGRUNTIME PyObject * SwigPyObject_New (void *ptr, swig_type_info *ty, int own)
SWIGRUNTIME void SwigPyObject_dealloc (PyObject *v)
SWIGRUNTIME PyObject * SwigPyObject_append (PyObject *v, PyObject *next)
SWIGRUNTIME PyObject * SwigPyObject_next (PyObject *v, PyObject *SWIGUNUSEDPARM(args))
SWIGINTERN PyObject * SwigPyObject_disown (PyObject *v, PyObject *SWIGUNUSEDPARM(args))
SWIGINTERN PyObject * SwigPyObject_acquire (PyObject *v, PyObject *SWIGUNUSEDPARM(args))
SWIGINTERN PyObject * SwigPyObject_own (PyObject *v, PyObject *args)
SWIGRUNTIME PyObject * SwigPyPacked_repr (SwigPyPacked *v)
SWIGRUNTIME PyObject * SwigPyPacked_str (SwigPyPacked *v)
SWIGRUNTIME int SwigPyPacked_compare (SwigPyPacked *v, SwigPyPacked *w)
SWIGRUNTIME PyTypeObject * SwigPyPacked_TypeOnce (void)
SWIGRUNTIME PyTypeObject * SwigPyPacked_type (void)
SWIGRUNTIMEINLINE int SwigPyPacked_Check (PyObject *op)
SWIGRUNTIME void SwigPyPacked_dealloc (PyObject *v)
SWIGRUNTIME PyObject * SwigPyPacked_New (void *ptr, size_t size, swig_type_info *ty)
SWIGRUNTIME swig_type_info * SwigPyPacked_UnpackData (PyObject *obj, void *ptr, size_t size)
SWIGRUNTIME PyObject * SWIG_This (void)
SWIGRUNTIME SwigPyObject * SWIG_Python_GetSwigThis (PyObject *pyobj)
SWIGRUNTIME int SWIG_Python_AcquirePtr (PyObject *obj, int own)
SWIGRUNTIME int SWIG_Python_ConvertPtrAndOwn (PyObject *obj, void **ptr, swig_type_info *ty, int flags, int *own)
SWIGRUNTIME int SWIG_Python_ConvertFunctionPtr (PyObject *obj, void **ptr, swig_type_info *ty)
SWIGRUNTIME int SWIG_Python_ConvertPacked (PyObject *obj, void *ptr, size_t sz, swig_type_info *ty)
SWIGRUNTIME PyObject * SWIG_Python_NewShadowInstance (SwigPyClientData *data, PyObject *swig_this)
SWIGRUNTIME void SWIG_Python_SetSwigThis (PyObject *inst, PyObject *swig_this)
SWIGINTERN PyObject * SWIG_Python_InitShadowInstance (PyObject *args)
SWIGRUNTIME PyObject * SWIG_Python_NewPointerObj (PyObject *self, void *ptr, swig_type_info *type, int flags)
SWIGRUNTIMEINLINE PyObject * SWIG_Python_NewPackedObj (void *ptr, size_t sz, swig_type_info *type)
SWIGRUNTIME swig_module_info * SWIG_Python_GetModule (void *SWIGUNUSEDPARM(clientdata))
SWIGRUNTIME void SWIG_Python_DestroyModule (PyObject *obj)
SWIGRUNTIME void SWIG_Python_SetModule (swig_module_info *swig_module)
SWIGRUNTIME PyObject * SWIG_Python_TypeCache (void)
SWIGRUNTIME swig_type_info * SWIG_Python_TypeQuery (const char *type)
SWIGRUNTIME int SWIG_Python_AddErrMesg (const char *mesg, int infront)
SWIGRUNTIME int SWIG_Python_ArgFail (int argnum)
SWIGRUNTIMEINLINE const char * SwigPyObject_GetDesc (PyObject *self)
SWIGRUNTIME void SWIG_Python_TypeError (const char *type, PyObject *obj)
SWIGRUNTIME void * SWIG_Python_MustGetPtr (PyObject *obj, swig_type_info *ty, int SWIGUNUSEDPARM(argnum), int flags)
SWIGRUNTIMEINLINE swig_type_info * SWIG_TypeQuery (const char *name)
SWIGRUNTIMEINLINE swig_type_info * SWIG_MangledTypeQuery (const char *name)
Variables
static PyMethodDef swigobject_methods []
static PyObject * Swig_This_global = NULL
Macro Definition Documentation
Py_hash_t
#define Py_hash_t long
Py_TYPE
#define Py_TYPE (op) ((op)->ob_type)
PyDescr_NAME
#define PyDescr_NAME (x) (((PyDescrObject *)(x))->d_name)
PyDescr_TYPE
#define PyDescr_TYPE (x) (((PyDescrObject *)(x))->d_type)
PyObject_DEL
#define PyObject_DEL PyObject_Del
SWIG_AcquirePtr
#define SWIG_AcquirePtr (ptr, src) SWIG_Python_AcquirePtr(ptr, src)
SWIG_AddCast
#define SWIG_AddCast (r) (r)
SWIG_AddNewMask
#define SWIG_AddNewMask (r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
SWIG_AddTmpMask
#define SWIG_AddTmpMask (r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
SWIG_arg_fail
#define SWIG_arg_fail (arg) SWIG_Python_ArgFail(arg)
SWIG_ArgError
#define SWIG_ArgError (r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
SWIG_AttributeError
#define SWIG_AttributeError -11
SWIG_BADOBJ
#define SWIG_BADOBJ (SWIG_ERROR)
SWIG_BUFFER_SIZE
#define SWIG_BUFFER_SIZE 1024
SWIG_BUILTIN_INIT
#define SWIG_BUILTIN_INIT (SWIG_BUILTIN_TP_INIT | SWIG_POINTER_OWN)
SWIG_BUILTIN_TP_INIT
#define SWIG_BUILTIN_TP_INIT (SWIG_POINTER_OWN << 2)
SWIG_CAST_NEW_MEMORY
#define SWIG_CAST_NEW_MEMORY 0x2
SWIG_CASTRANKLIMIT
#define SWIG_CASTRANKLIMIT (1 << 8)
SWIG_CheckImplicit
#define SWIG_CheckImplicit (ty) SWIG_Python_CheckImplicit(ty)
SWIG_CheckState
#define SWIG_CheckState (r) (SWIG_IsOK(r) ? 1 : 0)
SWIG_ConvertFunctionPtr
#define SWIG_ConvertFunctionPtr (obj, pptr, type) SWIG_Python_ConvertFunctionPtr(obj, pptr, type)
SWIG_ConvertInstance
#define SWIG_ConvertInstance (obj, pptr, type, flags) SWIG_ConvertPtr(obj, pptr, type, flags)
SWIG_ConvertMember
#define SWIG_ConvertMember (obj, ptr, sz, ty) SWIG_Python_ConvertPacked(obj, ptr, sz, ty)
SWIG_ConvertPacked
#define SWIG_ConvertPacked (obj, ptr, sz, ty) SWIG_Python_ConvertPacked(obj, ptr, sz, ty)
SWIG_ConvertPtr
#define SWIG_ConvertPtr (obj, pptr, type, flags) SWIG_Python_ConvertPtr(obj, pptr, type, flags)
SWIG_ConvertPtrAndOwn
#define SWIG_ConvertPtrAndOwn (obj, pptr, type, flags, own) SWIG_Python_ConvertPtrAndOwn(obj, pptr, type, flags, own)
SWIG_DelNewMask
#define SWIG_DelNewMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
SWIG_DelTmpMask
#define SWIG_DelTmpMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
SWIG_DivisionByZero
#define SWIG_DivisionByZero -6
SWIG_ERROR
#define SWIG_ERROR (-1)
SWIG_Error
#define SWIG_Error (code, msg) SWIG_Python_SetErrorMsg(SWIG_ErrorType(code), msg)
SWIG_ErrorType
#define SWIG_ErrorType (code) SWIG_Python_ErrorType(code)
SWIG_fail
#define SWIG_fail goto fail
SWIG_GetModule
#define SWIG_GetModule (clientdata) SWIG_Python_GetModule(clientdata)
SWIG_IndexError
#define SWIG_IndexError -4
SWIG_InternalNewPointerObj
#define SWIG_InternalNewPointerObj (ptr, type, flags) SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
SWIG_IOError
#define SWIG_IOError -2
SWIG_IsNewObj
#define SWIG_IsNewObj (r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
SWIG_IsOK
#define SWIG_IsOK (r) (r >= 0)
SWIG_IsTmpObj
#define SWIG_IsTmpObj (r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
SWIG_MemoryError
#define SWIG_MemoryError -12
SWIG_MustGetPtr
#define SWIG_MustGetPtr (p, type, argnum, flags) SWIG_Python_MustGetPtr(p, type, argnum, flags)
SWIG_NewClientData
#define SWIG_NewClientData (obj) SwigPyClientData_New(obj)
SWIG_NewFunctionPtrObj
#define SWIG_NewFunctionPtrObj (ptr, type) SWIG_Python_NewPointerObj(NULL, ptr, type, 0)
SWIG_NewInstanceObj
#define SWIG_NewInstanceObj (ptr, type, flags) SWIG_NewPointerObj(ptr, type, flags)
SWIG_NewMemberObj
#define SWIG_NewMemberObj (ptr, sz, type) SWIG_Python_NewPackedObj(ptr, sz, type)
SWIG_NEWOBJ
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
SWIG_NEWOBJMASK
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
SWIG_NewPackedObj
#define SWIG_NewPackedObj (ptr, sz, type) SWIG_Python_NewPackedObj(ptr, sz, type)
SWIG_NewPointerObj
#define SWIG_NewPointerObj (ptr, type, flags) SWIG_Python_NewPointerObj(NULL, ptr, type, flags)
SWIG_NullReferenceError
#define SWIG_NullReferenceError -13
SWIG_OK
#define SWIG_OK (0)
SWIG_OLDOBJ
#define SWIG_OLDOBJ (SWIG_OK)
SWIG_OverflowError
#define SWIG_OverflowError -7
swig_owntype
#define swig_owntype int
SWIG_POINTER_DISOWN
#define SWIG_POINTER_DISOWN 0x1
SWIG_POINTER_EXCEPTION
#define SWIG_POINTER_EXCEPTION 0
SWIG_POINTER_IMPLICIT_CONV
#define SWIG_POINTER_IMPLICIT_CONV (SWIG_POINTER_DISOWN << 1)
SWIG_POINTER_NEW
#define SWIG_POINTER_NEW (SWIG_POINTER_NOSHADOW | SWIG_POINTER_OWN)
SWIG_POINTER_NO_NULL
#define SWIG_POINTER_NO_NULL 0x4
SWIG_POINTER_NOSHADOW
#define SWIG_POINTER_NOSHADOW (SWIG_POINTER_OWN << 1)
SWIG_POINTER_OWN
#define SWIG_POINTER_OWN 0x1
SWIG_PY_BINARY
#define SWIG_PY_BINARY 5
SWIG_PY_POINTER
#define SWIG_PY_POINTER 4
SWIG_Python_CallFunctor
#define SWIG_Python_CallFunctor (functor, obj) PyObject_CallFunction(functor, (char *)"O", obj);
SWIG_Python_ConvertPtr
#define SWIG_Python_ConvertPtr (obj, pptr, type, flags) SWIG_Python_ConvertPtrAndOwn(obj, pptr, type, flags, 0)
SWIG_PYTHON_INITIALIZE_THREADS
#define SWIG_PYTHON_INITIALIZE_THREADS
SWIG_Python_Raise
#define SWIG_Python_Raise (obj, type, desc) SWIG_Python_SetErrorObj(SWIG_Python_ExceptionType(desc), obj)
SWIG_Python_str_DelForPy3
#define SWIG_Python_str_DelForPy3 (x)
SWIG_Python_str_FromFormat
#define SWIG_Python_str_FromFormat PyString_FromFormat
SWIG_PYTHON_THREAD_BEGIN_ALLOW
#define SWIG_PYTHON_THREAD_BEGIN_ALLOW
SWIG_PYTHON_THREAD_BEGIN_BLOCK
#define SWIG_PYTHON_THREAD_BEGIN_BLOCK
SWIG_PYTHON_THREAD_END_ALLOW
#define SWIG_PYTHON_THREAD_END_ALLOW
SWIG_PYTHON_THREAD_END_BLOCK
#define SWIG_PYTHON_THREAD_END_BLOCK
SWIG_RUNTIME_VERSION
#define SWIG_RUNTIME_VERSION "4"
SWIG_RuntimeError
#define SWIG_RuntimeError -3
SWIG_SetErrorMsg
#define SWIG_SetErrorMsg SWIG_Python_SetErrorMsg
SWIG_SetErrorObj
#define SWIG_SetErrorObj SWIG_Python_SetErrorObj
SWIG_SetModule
#define SWIG_SetModule (clientdata, pointer) SWIG_Python_SetModule(pointer)
SWIG_STATIC_POINTER
#define SWIG_STATIC_POINTER (var) var = 0; if (!var) var
SWIG_SyntaxError
#define SWIG_SyntaxError -8
SWIG_SystemError
#define SWIG_SystemError -10
SWIG_TMPOBJ
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
SWIG_TMPOBJMASK
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
SWIG_TYPE_TABLE_NAME
#define SWIG_TYPE_TABLE_NAME
SWIG_TypeError
#define SWIG_TypeError -5
SWIG_UnknownError
#define SWIG_UnknownError -1
SWIG_ValueError
#define SWIG_ValueError -9
SWIGEXPORT
#define SWIGEXPORT
SWIGINLINE
#define SWIGINLINE
SWIGINTERN
#define SWIGINTERN static SWIGUNUSED
SWIGINTERNINLINE
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
SWIGPY_CAPSULE_NAME
#define SWIGPY_CAPSULE_NAME ("swig_runtime_data" SWIG_RUNTIME_VERSION ".type_pointer_capsule" SWIG_TYPE_TABLE_NAME)
SWIGPY_USE_CAPSULE
#define SWIGPY_USE_CAPSULE
SWIGRUNTIME
#define SWIGRUNTIME SWIGINTERN
SWIGRUNTIMEINLINE
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
SWIGSTDCALL
#define SWIGSTDCALL
SWIGTEMPLATEDISAMBIGUATOR
#define SWIGTEMPLATEDISAMBIGUATOR
SWIGUNUSED
#define SWIGUNUSED
SWIGUNUSEDPARM
#define SWIGUNUSEDPARM (p) p SWIGUNUSED
Typedef Documentation
swig_cast_info
typedef struct swig_cast_info swig_cast_info
swig_const_info
typedef struct swig_const_info swig_const_info
swig_converter_func
typedef void *(* swig_converter_func) (void *, int *)
swig_dycast_func
typedef struct swig_type_info *(* swig_dycast_func) (void **)
swig_module_info
typedef struct swig_module_info swig_module_info
swig_type_info
typedef struct swig_type_info swig_type_info
Function Documentation
SWIG_MangledTypeQuery()
SWIGRUNTIMEINLINE swig_type_info * SWIG_MangledTypeQuery (const char * name)
References SWIG_GetModule, and SWIG_MangledTypeQueryModule().
SWIG_MangledTypeQueryModule()
SWIGRUNTIME swig_type_info * SWIG_MangledTypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
References swig_type_info::name, swig_module_info::next, swig_module_info::size, and swig_module_info::types.
Referenced by SWIG_MangledTypeQuery(), and SWIG_TypeQueryModule().
SWIG_PackData()
SWIGRUNTIME char * SWIG_PackData (char * c, void * ptr, size_t sz)
Referenced by SWIG_PackDataName(), and SWIG_PackVoidPtr().
SWIG_PackDataName()
SWIGRUNTIME char * SWIG_PackDataName (char * buff, void * ptr, size_t sz, const char * name, size_t bsz)
References SWIG_PackData().
Referenced by SwigPyPacked_repr(), and SwigPyPacked_str().
SWIG_PackVoidPtr()
SWIGRUNTIME char * SWIG_PackVoidPtr (char * buff, void * ptr, const char * name, size_t bsz)
References SWIG_PackData().
SWIG_Py_Void()
SWIGRUNTIMEINLINE PyObject * SWIG_Py_Void (void)
Referenced by SWIG_Python_InitShadowInstance(), SWIG_Python_NewPackedObj(), SWIG_Python_NewPointerObj(), SwigPyObject_acquire(), SwigPyObject_append(), SwigPyObject_disown(), and SwigPyObject_next().
SWIG_Python_AcquirePtr()
SWIGRUNTIME int SWIG_Python_AcquirePtr (PyObject * obj, int own)
References SwigPyObject::own, SWIG_POINTER_OWN, and SWIG_Python_GetSwigThis().
SWIG_Python_AddErrMesg()
SWIGRUNTIME int SWIG_Python_AddErrMesg (const char * mesg, int infront)
References SWIG_Python_str_AsChar(), and SWIG_Python_str_DelForPy3.
Referenced by SWIG_Python_ArgFail().
SWIG_Python_AddErrorMsg()
SWIGRUNTIME void SWIG_Python_AddErrorMsg (const char * mesg)
References SWIG_Python_str_AsChar(), and SWIG_Python_str_DelForPy3.
SWIG_Python_AppendOutput()
SWIGINTERN PyObject * SWIG_Python_AppendOutput (PyObject * result, PyObject * obj)
SWIG_Python_ArgFail()
SWIGRUNTIME int SWIG_Python_ArgFail (int argnum)
References SWIG_Python_AddErrMesg().
Referenced by SWIG_Python_MustGetPtr().
SWIG_Python_CheckImplicit()
SWIGRUNTIMEINLINE int SWIG_Python_CheckImplicit (swig_type_info * ty)
References swig_type_info::clientdata, and SwigPyClientData::implicitconv.
SWIG_Python_ConvertFunctionPtr()
SWIGRUNTIME int SWIG_Python_ConvertFunctionPtr (PyObject * obj, void ** ptr, swig_type_info * ty)
References swig_type_info::name, SWIG_ConvertPtr, SWIG_ERROR, SWIG_OK, SWIG_TypeCast(), SWIG_TypeCheck(), and SWIG_UnpackVoidPtr().
SWIG_Python_ConvertPacked()
SWIGRUNTIME int SWIG_Python_ConvertPacked (PyObject * obj, void * ptr, size_t sz, swig_type_info * ty)
References swig_type_info::name, SWIG_ERROR, SWIG_OK, SWIG_TypeCheck(), and SwigPyPacked_UnpackData().
SWIG_Python_ConvertPtrAndOwn()
SWIGRUNTIME int SWIG_Python_ConvertPtrAndOwn (PyObject * obj, void ** ptr, swig_type_info * ty, int flags, int * own)
References swig_type_info::clientdata, SwigPyClientData::implicitconv, SwigPyClientData::klass, swig_type_info::name, SwigPyObject::next, SwigPyObject::own, SwigPyObject::ptr, SWIG_AddCast, SWIG_AddNewMask, SWIG_CAST_NEW_MEMORY, SWIG_ERROR, SWIG_IsOK, SWIG_NullReferenceError, SWIG_OK, SWIG_POINTER_DISOWN, SWIG_POINTER_IMPLICIT_CONV, SWIG_POINTER_NO_NULL, SWIG_Python_CallFunctor, SWIG_Python_ConvertPtrAndOwn(), SWIG_Python_GetSwigThis(), SWIG_TypeCast(), SWIG_TypeCheck(), and SwigPyObject::ty.
Referenced by SWIG_Python_ConvertPtrAndOwn().
SWIG_Python_DestroyModule()
SWIGRUNTIME void SWIG_Python_DestroyModule (PyObject * obj)
References swig_type_info::clientdata, swig_type_info::owndata, swig_module_info::size, SWIG_This(), Swig_This_global, SWIGPY_CAPSULE_NAME, SwigPyClientData_Del(), and swig_module_info::types.
Referenced by SWIG_Python_SetModule().
SWIG_Python_ErrorType()
SWIGRUNTIME PyObject * SWIG_Python_ErrorType (int code)
References SWIG_AttributeError, SWIG_DivisionByZero, SWIG_IndexError, SWIG_IOError, SWIG_MemoryError, SWIG_OverflowError, SWIG_RuntimeError, SWIG_SyntaxError, SWIG_SystemError, SWIG_TypeError, and SWIG_ValueError.
SWIG_Python_ExceptionType()
SWIGRUNTIMEINLINE PyObject * SWIG_Python_ExceptionType (swig_type_info * desc)
References swig_type_info::clientdata, and SwigPyClientData::klass.
SWIG_Python_GetModule()
SWIGRUNTIME swig_module_info * SWIG_Python_GetModule (void * SWIGUNUSEDPARMclientdata)
References SWIGPY_CAPSULE_NAME.
SWIG_Python_GetSwigThis()
SWIGRUNTIME SwigPyObject * SWIG_Python_GetSwigThis (PyObject * pyobj)
References SWIG_Python_GetSwigThis(), SWIG_This(), and SwigPyObject_Check().
Referenced by SWIG_Python_AcquirePtr(), SWIG_Python_ConvertPtrAndOwn(), SWIG_Python_GetSwigThis(), and SWIG_Python_InitShadowInstance().
SWIG_Python_InitShadowInstance()
SWIGINTERN PyObject * SWIG_Python_InitShadowInstance (PyObject * args)
References SWIG_Py_Void(), SWIG_Python_GetSwigThis(), SWIG_Python_SetSwigThis(), SWIG_Python_UnpackTuple(), and SwigPyObject_append().
SWIG_Python_MustGetPtr()
SWIGRUNTIME void * SWIG_Python_MustGetPtr (PyObject * obj, swig_type_info * ty, int SWIGUNUSEDPARMargnum, int flags)
References SWIG_Python_ArgFail(), SWIG_Python_ConvertPtr, SWIG_Python_TypeError(), and SWIG_TypePrettyName().
SWIG_Python_NewPackedObj()
SWIGRUNTIMEINLINE PyObject * SWIG_Python_NewPackedObj (void * ptr, size_t sz, swig_type_info * type)
References SWIG_Py_Void(), and SwigPyPacked_New().
SWIG_Python_NewPointerObj()
SWIGRUNTIME PyObject * SWIG_Python_NewPointerObj (PyObject * self, void * ptr, swig_type_info * type, int flags)
References swig_type_info::clientdata, SwigPyObject::next, SwigPyObject::own, SwigPyObject::ptr, SwigPyClientData::pytype, SWIG_BUILTIN_TP_INIT, SWIG_POINTER_NOSHADOW, SWIG_POINTER_OWN, SWIG_Py_Void(), SWIG_Python_NewShadowInstance(), SwigPyObject_New(), and SwigPyObject::ty.
SWIG_Python_NewShadowInstance()
SWIGRUNTIME PyObject * SWIG_Python_NewShadowInstance (SwigPyClientData * data, PyObject * swig_this)
References SwigPyClientData::newargs, SwigPyClientData::newraw, Py_TYPE, and SWIG_This().
Referenced by SWIG_Python_NewPointerObj().
SWIG_Python_RaiseOrModifyTypeError()
SWIGRUNTIME void SWIG_Python_RaiseOrModifyTypeError (const char * message)
References SWIG_Python_TypeErrorOccurred().
SWIG_Python_SetConstant()
SWIGINTERN void SWIG_Python_SetConstant (PyObject * d, const char * name, PyObject * obj)
SWIG_Python_SetErrorMsg()
SWIGINTERN void SWIG_Python_SetErrorMsg (PyObject * errtype, const char * msg)
References SWIG_PYTHON_THREAD_BEGIN_BLOCK, and SWIG_PYTHON_THREAD_END_BLOCK.
SWIG_Python_SetErrorObj()
SWIGINTERN void SWIG_Python_SetErrorObj (PyObject * errtype, PyObject * obj)
References SWIG_PYTHON_THREAD_BEGIN_BLOCK, and SWIG_PYTHON_THREAD_END_BLOCK.
SWIG_Python_SetModule()
SWIGRUNTIME void SWIG_Python_SetModule (swig_module_info * swig_module)
References SWIG_Python_DestroyModule(), SWIG_RUNTIME_VERSION, SWIG_TYPE_TABLE_NAME, and SWIGPY_CAPSULE_NAME.
SWIG_Python_SetSwigThis()
SWIGRUNTIME void SWIG_Python_SetSwigThis (PyObject * inst, PyObject * swig_this)
References SWIG_This().
Referenced by SWIG_Python_InitShadowInstance().
SWIG_Python_str_AsChar()
SWIGINTERN char * SWIG_Python_str_AsChar (PyObject * str)
Referenced by SWIG_Python_AddErrMesg(), SWIG_Python_AddErrorMsg(), and SWIG_Python_TypeError().
SWIG_Python_str_FromChar()
SWIGINTERN PyObject * SWIG_Python_str_FromChar (const char * c)
Referenced by SWIG_Python_TypeQuery(), SWIG_This(), SwigPyObject_format(), and SwigPyPacked_str().
SWIG_Python_TypeCache()
SWIGRUNTIME PyObject * SWIG_Python_TypeCache (void)
References SWIG_STATIC_POINTER.
Referenced by SWIG_Python_TypeQuery().
SWIG_Python_TypeError()
SWIGRUNTIME void SWIG_Python_TypeError (const char * type, PyObject * obj)
References SWIG_Python_str_AsChar(), SWIG_Python_str_DelForPy3, SwigPyObject_Check(), and SwigPyObject_GetDesc().
Referenced by SWIG_Python_MustGetPtr().
SWIG_Python_TypeErrorOccurred()
SWIGRUNTIME int SWIG_Python_TypeErrorOccurred (PyObject * obj)
Referenced by SWIG_Python_RaiseOrModifyTypeError().
SWIG_Python_TypeQuery()
SWIGRUNTIME swig_type_info * SWIG_Python_TypeQuery (const char * type)
References SWIG_GetModule, SWIG_Python_str_FromChar(), SWIG_Python_TypeCache(), and SWIG_TypeQueryModule().
SWIG_Python_UnpackTuple()
SWIGINTERN Py_ssize_t SWIG_Python_UnpackTuple (PyObject * args, const char * name, Py_ssize_t min, Py_ssize_t max, PyObject ** objs)
Referenced by SWIG_Python_InitShadowInstance().
SWIG_This()
SWIGRUNTIME PyObject * SWIG_This (void)
References SWIG_Python_str_FromChar(), and Swig_This_global.
Referenced by SWIG_Python_DestroyModule(), SWIG_Python_GetSwigThis(), SWIG_Python_NewShadowInstance(), and SWIG_Python_SetSwigThis().
SWIG_TypeCast()
SWIGRUNTIMEINLINE void * SWIG_TypeCast (swig_cast_info * ty, void * ptr, int * newmemory)
References swig_cast_info::converter.
Referenced by SWIG_Python_ConvertFunctionPtr(), and SWIG_Python_ConvertPtrAndOwn().
SWIG_TypeCheck()
SWIGRUNTIME swig_cast_info * SWIG_TypeCheck (const char * c, swig_type_info * ty)
References swig_type_info::cast, swig_type_info::name, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
Referenced by SWIG_Python_ConvertFunctionPtr(), SWIG_Python_ConvertPacked(), and SWIG_Python_ConvertPtrAndOwn().
SWIG_TypeCheckStruct()
SWIGRUNTIME swig_cast_info * SWIG_TypeCheckStruct (swig_type_info * from, swig_type_info * ty)
References swig_type_info::cast, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
SWIG_TypeClientData()
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info * ti, void * clientdata)
References swig_type_info::cast, swig_type_info::clientdata, swig_module_info::clientdata, swig_cast_info::converter, swig_cast_info::next, SWIG_TypeClientData(), and swig_cast_info::type.
Referenced by SWIG_TypeClientData(), and SWIG_TypeNewClientData().
SWIG_TypeCmp()
SWIGRUNTIME int SWIG_TypeCmp (const char * nb, const char * tb)
References SWIG_TypeNameComp().
Referenced by SWIG_TypeEquiv().
SWIG_TypeDynamicCast()
SWIGRUNTIME swig_type_info * SWIG_TypeDynamicCast (swig_type_info * ty, void ** ptr)
References swig_type_info::dcast.
SWIG_TypeEquiv()
SWIGRUNTIME int SWIG_TypeEquiv (const char * nb, const char * tb)
References SWIG_TypeCmp().
Referenced by SWIG_TypeQueryModule().
SWIG_TypeName()
SWIGRUNTIMEINLINE const char * SWIG_TypeName (const swig_type_info * ty)
References swig_type_info::name.
SWIG_TypeNameComp()
SWIGRUNTIME int SWIG_TypeNameComp (const char * f1, const char * l1, const char * f2, const char * l2)
Referenced by SWIG_TypeCmp().
SWIG_TypeNewClientData()
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info * ti, void * clientdata)
References swig_module_info::clientdata, swig_type_info::owndata, and SWIG_TypeClientData().
SWIG_TypePrettyName()
SWIGRUNTIME const char * SWIG_TypePrettyName (const swig_type_info * type)
References swig_type_info::name, and swig_type_info::str.
Referenced by SWIG_Python_MustGetPtr(), SwigPyObject_dealloc(), and SwigPyObject_repr().
SWIG_TypeQuery()
SWIGRUNTIMEINLINE swig_type_info * SWIG_TypeQuery (const char * name)
References SWIG_GetModule, and SWIG_TypeQueryModule().
SWIG_TypeQueryModule()
SWIGRUNTIME swig_type_info * SWIG_TypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
References swig_module_info::next, swig_module_info::size, swig_type_info::str, SWIG_MangledTypeQueryModule(), SWIG_TypeEquiv(), and swig_module_info::types.
Referenced by SWIG_Python_TypeQuery(), and SWIG_TypeQuery().
SWIG_UnpackData()
SWIGRUNTIME const char * SWIG_UnpackData (const char * c, void * ptr, size_t sz)
Referenced by SWIG_UnpackDataName(), and SWIG_UnpackVoidPtr().
SWIG_UnpackDataName()
SWIGRUNTIME const char * SWIG_UnpackDataName (const char * c, void * ptr, size_t sz, const char * name)
References SWIG_UnpackData().
SWIG_UnpackVoidPtr()
SWIGRUNTIME const char * SWIG_UnpackVoidPtr (const char * c, void ** ptr, const char * name)
References SWIG_UnpackData().
Referenced by SWIG_Python_ConvertFunctionPtr().
SwigPyClientData_Del()
SWIGRUNTIME void SwigPyClientData_Del (SwigPyClientData * data)
References SwigPyClientData::destroy, SwigPyClientData::newargs, and SwigPyClientData::newraw.
Referenced by SWIG_Python_DestroyModule().
SwigPyClientData_New()
SWIGRUNTIME SwigPyClientData * SwigPyClientData_New (PyObject * obj)
References SwigPyClientData::delargs, SwigPyClientData::destroy, SwigPyClientData::implicitconv, SwigPyClientData::klass, SwigPyClientData::newargs, SwigPyClientData::newraw, and SwigPyClientData::pytype.
SwigPyObject_acquire()
SWIGINTERN PyObject * SwigPyObject_acquire (PyObject * v, PyObject * SWIGUNUSEDPARMargs)
References SwigPyObject::own, SWIG_POINTER_OWN, and SWIG_Py_Void().
Referenced by SwigPyObject_own().
SwigPyObject_append()
SWIGRUNTIME PyObject * SwigPyObject_append (PyObject * v, PyObject * next)
References SwigPyObject::next, SWIG_Py_Void(), and SwigPyObject_Check().
Referenced by SWIG_Python_InitShadowInstance().
SwigPyObject_Check()
SWIGRUNTIMEINLINE int SwigPyObject_Check (PyObject * op)
References Py_TYPE, and SwigPyObject_type().
Referenced by SWIG_Python_GetSwigThis(), SWIG_Python_TypeError(), and SwigPyObject_append().
SwigPyObject_compare()
SWIGRUNTIME int SwigPyObject_compare (SwigPyObject * v, SwigPyObject * w)
References SwigPyObject::ptr.
Referenced by SwigPyObject_richcompare(), and SwigPyObject_TypeOnce().
SwigPyObject_dealloc()
SWIGRUNTIME void SwigPyObject_dealloc (PyObject * v)
References swig_type_info::clientdata, SwigPyClientData::delargs, SwigPyClientData::destroy, SwigPyObject::next, SwigPyObject::own, SwigPyObject::ptr, PyObject_DEL, SWIG_POINTER_OWN, SWIG_Python_CallFunctor, SWIG_TypePrettyName(), SwigPyObject_New(), and SwigPyObject::ty.
Referenced by SwigPyObject_TypeOnce().
SwigPyObject_disown()
SWIGINTERN PyObject * SwigPyObject_disown (PyObject * v, PyObject * SWIGUNUSEDPARMargs)
References SwigPyObject::own, and SWIG_Py_Void().
Referenced by SwigPyObject_own().
SwigPyObject_format()
SWIGRUNTIME PyObject * SwigPyObject_format (const char * fmt, SwigPyObject * v)
References SWIG_Python_str_FromChar(), and SwigPyObject_long().
Referenced by SwigPyObject_hex(), and SwigPyObject_oct().
SwigPyObject_GetDesc()
SWIGRUNTIMEINLINE const char * SwigPyObject_GetDesc (PyObject * self)
References swig_type_info::str, and SwigPyObject::ty.
Referenced by SWIG_Python_TypeError().
SwigPyObject_hex()
SWIGRUNTIME PyObject * SwigPyObject_hex (SwigPyObject * v)
References SwigPyObject_format().
Referenced by SwigPyObject_TypeOnce().
SwigPyObject_long()
SWIGRUNTIME PyObject * SwigPyObject_long (SwigPyObject * v)
References SwigPyObject::ptr.
Referenced by SwigPyObject_format(), and SwigPyObject_TypeOnce().
SwigPyObject_New()
SWIGRUNTIME PyObject * SwigPyObject_New (void * ptr, swig_type_info * ty, int own)
References SwigPyObject::next, SwigPyObject::own, SwigPyObject::ptr, SwigPyObject_type(), and SwigPyObject::ty.
Referenced by SWIG_Python_NewPointerObj(), and SwigPyObject_dealloc().
SwigPyObject_next()
SWIGRUNTIME PyObject * SwigPyObject_next (PyObject * v, PyObject * SWIGUNUSEDPARMargs)
References SwigPyObject::next, and SWIG_Py_Void().
SwigPyObject_oct()
SWIGRUNTIME PyObject * SwigPyObject_oct (SwigPyObject * v)
References SwigPyObject_format().
Referenced by SwigPyObject_TypeOnce().
SwigPyObject_own()
SWIGINTERN PyObject * SwigPyObject_own (PyObject * v, PyObject * args)
References SwigPyObject::own, SwigPyObject_acquire(), and SwigPyObject_disown().
SwigPyObject_repr()
SWIGRUNTIME PyObject * SwigPyObject_repr (SwigPyObject * v)
References SwigPyObject::next, SWIG_Python_str_FromFormat, SWIG_TypePrettyName(), SwigPyObject_repr(), and SwigPyObject::ty.
Referenced by SwigPyObject_repr(), SwigPyObject_repr2(), and SwigPyObject_TypeOnce().
SwigPyObject_repr2()
SWIGRUNTIME PyObject * SwigPyObject_repr2 (PyObject * v, PyObject * SWIGUNUSEDPARMargs)
References SwigPyObject_repr().
SwigPyObject_richcompare()
SWIGRUNTIME PyObject * SwigPyObject_richcompare (SwigPyObject * v, SwigPyObject * w, int op)
References SwigPyObject_compare().
Referenced by SwigPyObject_TypeOnce().
SwigPyObject_type()
SWIGRUNTIME PyTypeObject * SwigPyObject_type (void)
References SWIG_STATIC_POINTER, and SwigPyObject_TypeOnce().
Referenced by SwigPyObject_Check(), and SwigPyObject_New().
SwigPyObject_TypeOnce()
SWIGRUNTIME PyTypeObject * SwigPyObject_TypeOnce (void)
References swigobject_methods, SwigPyObject_compare(), SwigPyObject_dealloc(), SwigPyObject_hex(), SwigPyObject_long(), SwigPyObject_oct(), SwigPyObject_repr(), and SwigPyObject_richcompare().
Referenced by SwigPyObject_type().
SwigPyPacked_Check()
SWIGRUNTIMEINLINE int SwigPyPacked_Check (PyObject * op)
References SwigPyPacked_TypeOnce().
Referenced by SwigPyPacked_dealloc(), and SwigPyPacked_UnpackData().
SwigPyPacked_compare()
SWIGRUNTIME int SwigPyPacked_compare (SwigPyPacked * v, SwigPyPacked * w)
References SwigPyPacked::pack, and SwigPyPacked::size.
Referenced by SwigPyPacked_TypeOnce().
SwigPyPacked_dealloc()
SWIGRUNTIME void SwigPyPacked_dealloc (PyObject * v)
References SwigPyPacked::pack, PyObject_DEL, and SwigPyPacked_Check().
Referenced by SwigPyPacked_TypeOnce().
SwigPyPacked_New()
SWIGRUNTIME PyObject * SwigPyPacked_New (void * ptr, size_t size, swig_type_info * ty)
References SwigPyPacked::pack, PyObject_DEL, SwigPyPacked::size, SwigPyPacked_type(), and SwigPyPacked::ty.
Referenced by SWIG_Python_NewPackedObj().
SwigPyPacked_repr()
SWIGRUNTIME PyObject * SwigPyPacked_repr (SwigPyPacked * v)
References swig_type_info::name, SwigPyPacked::pack, SwigPyPacked::size, SWIG_BUFFER_SIZE, SWIG_PackDataName(), SWIG_Python_str_FromFormat, and SwigPyPacked::ty.
Referenced by SwigPyPacked_TypeOnce().
SwigPyPacked_str()
SWIGRUNTIME PyObject * SwigPyPacked_str (SwigPyPacked * v)
References swig_type_info::name, SwigPyPacked::pack, SwigPyPacked::size, SWIG_BUFFER_SIZE, SWIG_PackDataName(), SWIG_Python_str_FromChar(), SWIG_Python_str_FromFormat, and SwigPyPacked::ty.
Referenced by SwigPyPacked_TypeOnce().
SwigPyPacked_type()
SWIGRUNTIME PyTypeObject * SwigPyPacked_type (void)
References SWIG_STATIC_POINTER, and SwigPyPacked_TypeOnce().
Referenced by SwigPyPacked_New().
SwigPyPacked_TypeOnce()
SWIGRUNTIME PyTypeObject * SwigPyPacked_TypeOnce (void)
References SwigPyPacked_compare(), SwigPyPacked_dealloc(), SwigPyPacked_repr(), and SwigPyPacked_str().
Referenced by SwigPyPacked_Check(), and SwigPyPacked_type().
SwigPyPacked_UnpackData()
SWIGRUNTIME swig_type_info * SwigPyPacked_UnpackData (PyObject * obj, void * ptr, size_t size)
References SwigPyPacked::pack, SwigPyPacked::size, SwigPyPacked_Check(), and SwigPyPacked::ty.
Referenced by SWIG_Python_ConvertPacked().
Variable Documentation
Swig_This_global
PyObject* Swig_This_global = NULL static
Referenced by SWIG_Python_DestroyModule(), and SWIG_This().
swigobject_methods
PyMethodDef swigobject_methods[] static
Initial value:
= {
  {"disown",  SwigPyObject_disown,  METH_NOARGS,  "releases ownership of the pointer"},
  {"acquire", SwigPyObject_acquire, METH_NOARGS,  "acquires ownership of the pointer"},
  {"own",     SwigPyObject_own,     METH_VARARGS, "returns/sets ownership of the pointer"},
  {"append",  SwigPyObject_append,  METH_O,       "appends another 'this' object"},
  {"next",    SwigPyObject_next,    METH_NOARGS,  "returns the next 'this' object"},
  {"__repr__",SwigPyObject_repr2,   METH_NOARGS,  "returns object representation"},
  {0, 0, 0, 0}
}
Referenced by SwigPyObject_TypeOnce().